### ISSUE TITLE
Graph API

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-deps#69]
I think we should abandon internal format.

**API with internal format**

```js
const resolve = require('bem-deps').resolve;

const decl = [{ block: 'A' }];
const deps = [
    {
        entity: { block: 'A' },
        dependOn: [
            {
                entity: { block: 'B' }
            }
        ]
    },
    {
        entity: { block: 'B' },
        dependOn: [
            {
                entity: { block: 'C' },
                order: 'dependenceBeforeDependants'
            }
        ]
    },
    {
        entity: { block: 'C' },
        tech: 'js',
        dependOn: [
            {
                entity: { block: 'D' },
                tech: 'bemhtml'
            }
        ]
    }
];
      
const resolved = resolve(decl, deps);
```

**Graph API**

```js
const DependencyGraph = require('bem-deps').DependencyGraph;
const graph = new DependencyGraph();

graph
    .node({ block: 'A' })
    .addDependency({ block: 'B' });

graph
    .node({ block: 'B' })
    .addDependency({ block: 'C' }, { ordered: true });

graph
    .node({ block: 'C' }, { tech: 'js' })
    .addDependency({ block: 'D' }, { tech: 'bemhtml' });

graph.dependenciesOf({ block: 'A' }, { tech: 'js' });
```

**Methods:**

* `graph.node(entity[, { tech: string }])` — gets or adds BEM entity part to graph. 

  Returns `GraphNode` instance. 

  If `tech`  is not specified, adds entity part with common (*) tech.

* `graph.addDependency(dependence[, { tech: string, ordered: boolean }])` — add dependency from node entity part to dependence entity part.

  If `tech`  is not specified, adds dependency to dependence with common (*) tech.
  
  If `ordered: true`, adds note that dependence will be added before dependants (old `order: dependenceBeforeDependants`).

* `graph.dependenciesOf(entity[, { tech: string })` — resolve dependencies for specified tech.

  Returns `{ entities: iterator, dependOn: object }`.

  If `tech`  is not specified, dependencies will be resolve for common tech.

* `graph.entityParts({ tech: string })` — returns all entity parts in graph for specified tech.

  Returns iterator with entity parts.

  If `tech`  is not specified, returns entity parts with common tech.

* `graph.sortedEntityParts({ tech: string })` — like `graph.sortedEntityParts()`, but sorted by dependency rules (like `graph.dependenciesOf`).

  Equivalently `graph.dependenciesOf(graph.entityParts())`.

### Why?

* The Graph API looks easier.
* We should not create data in special format to resolve dependencies.
* We can faster to parse other formats.
* We can parse all deps once and resolve many times (before we should parse inner format every time we had resolve dependencies).
* We can add helpers like `entityParts` and `sortedEntityParts`.

**Comment by zxqfox** [comment]
That's a huge change actually. Not a bad one but a really huge. 

Can you please explain reasons more widely?
It doesn't look easier for me than specification. Clear specification is literally the same as clear API to me.
It's not clear how we can do it faster.
Not sure why we can't convert anything to graph to resolve many times atm. It doesn't rely on the public API.
Query language can be any with any input format. It doesn't rely again on the public API.

**Comment by zxqfox** [comment]
After a meeting I suggest to use this API:
- `graph.node(entity)` — as you suggested just without the second `{?{tech: string}}` argument
- `node.dependOn(dependentEntity[, { techs: ?[string, string], ordered: boolean }])`
  passed `techs` means depsByTech: the first string requires the later ones:<br>
  `graph.node({block: 'a'}).dependOn({block: 'b'}).dependOn({block: 'c'}, { techs: ['js', 'tmpl'] });`
  and if techs were not specified we add the common edge (any to the same), and if specified, we add additional edges with the first to the later ones.

Need additional research here ;-(

**Comment by zxqfox** [comment]
Guess it's resolved as http://github.com/bem-sdk/bem-graph package
