### ISSUE TITLE
Unwished elem in fulfilling tenoroks

### ISSUE THREAD

**Issue by zxqfox** [bem-sdk/bem-deps#71]
https://github.com/bem-sdk/bem-deps/blob/master/lib/formats/deps.js/reader.js#L24

Can be fixed with swapping lines and adding `entity.block ||` to `entity.elem || (…)` like that:

``` js
                dep[depsType].forEach(function (entity) {
                    entity.block || entity.elem || (entity.elem = file.entity.elem);
                    entity.block || (entity.block = file.entity.block);
                });
```

Otherwise it adds unwished elem to dependent blocks:

``` js
({
    block: 'header',
    elem: 'logo',
    shouldDeps: [{
        block: 'logo' // It will require now logo__logo
    }]
});
```

**Comment by skad0** [comment]
Fixed in https://github.com/bem-sdk/bem-decl/pull/50 ([tests](https://github.com/bem-sdk/bem-decl/blob/master/test/assign.test.js))?
@zxqfox

**Comment by skad0** [comment]
Covered with tests [here](https://github.com/bem-sdk/bem-decl/pull/102)
