### ISSUE TITLE
Add support for different levels namings & schemes

### ISSUE THREAD

**Issue by shkarupa-alex** [bem-sdk/bem-deps#91]
bem-deps uses bem-walk inside gather function https://github.com/bem-sdk/bem-deps/blob/master/lib/gather.js

But now there is no way to provide levelsMap to bem-walk. 
```javascript
const walker = walk(config.levels, { defaults: config.options });
```

This line should look like 
```javascript
const walker = walk(config.levels, { levels: config.options.levels, defaults: config.options });
```

**Comment by zxqfox** [comment]
Nice catch! Would be great if you provide a PR ;-)
